# Problem Statement

## From Researcher
This dataset gathered SSVEP-BCI recordings of 35 healthy subjects (17 females, aged 17-34 years, mean age: 22 years) focusing on 40 characters flickering at different frequencies (8-15.8 Hz with an interval of 0.2 Hz). For each subject, the experiment consisted of 6 blocks. Each block contained 40 trials corresponding to all 40 characters indicated in a random order. Each trial started with a visual cue (a red square) indicating a target stimulus. The cue appeared for 0.5 s on the screen. Subjects were asked to shift their gaze to the target as soon as possible within the cue duration. Following the cue offset, all stimuli started to flicker on the screen concurrently and lasted 5 s. After stimulus offset, the screen was blank for 0.5 s before the next trial began, which allowed the subjects to have short breaks between consecutive trials. Each trial lasted a total of 6 s. To facilitate visual fixation, a red triangle appeared below the flickering target during the stimulation period. In each block, subjects were asked to avoid eye blinks during the stimulation period. To avoid visual fatigue, there was a rest for several minutes between two consecutive blocks.

EEG data were acquired using a Synamps2 system (Neuroscan, Inc.) with a sampling rate of 1000 Hz. The amplifier frequency passband ranged from 0.15 Hz to 200 Hz. Sixty-four channels covered the whole scalp of the subject and were aligned according to the international 10-20 system. The ground was placed on midway between Fz and FPz. The reference was located on the vertex. Electrode impedances were kept below 10 K¶∏. To remove the common power-line noise, a notch filter at 50 Hz was applied in data recording. Event triggers generated by the computer to the amplifier and recorded on an event channel synchronized to the EEG data. 

The continuous EEG data was segmented into 6 s epochs (500 ms pre-stimulus, 5.5 s post-stimulus onset). The epochs were subsequently downsampled to 250 Hz. Thus each trial consisted of 1500 time points. Finally, these data were stored as double-precision floating-point values in MATLAB and were named as subject indices (i.e., S01.mat, °≠, S35.mat). For each file, the data loaded in MATLAB generate a 4-D matrix named °Ædata°Ø with dimensions of [64, 1500, 40, 6]. The four dimensions indicate °ÆElectrode index°Ø, °ÆTime points°Ø, °ÆTarget index°Ø, and °ÆBlock index°Ø. The electrode positions were saved in a °Æ64-channels.loc°Ø file. Six trials were available for each SSVEP frequency. Frequency and phase values for the 40 target indices were saved in a °ÆFreq_Phase.mat°Ø file.

Information for all subjects was listed in a °ÆSub_info.txt°Ø file. For each subject, there are five factors including °ÆSubject Index°Ø, °ÆGender°Ø, °ÆAge°Ø, °ÆHandedness°Ø, and °ÆGroup°Ø. Subjects were divided into an °Æexperienced°Ø group (eight subjects, S01-S08) and a °Ænaive°Ø group (27 subjects, S09-S35) according to their experience in SSVEP-based BCIs.

## Summary
1.วัดหัว 64 จุด sampling rate 250 Hz

2.มีคน 35 คน แต่ละคนทำการทดลอง 6 blocks มีเวลาพัก 2-3 mins ระหว่าง block ที่ติดกันครับ

3.ใน 1 Block ประกอบ 40 trials (40 frequencies & phases as presented in an image, random sequence) แต่ละ trial สัญญาณยาว 6 วินาที

4.ใน 1 trial ประกอบไปด้วย 0.5s สำหรับ cue ว่าให้มองที่ไหนจาก 1ใน 40 เป้าหมาย, 5s การ stimulation สมองด้วยความถี่และเฟสนั้นๆ, หลังจากนั้น0.5s จอว่าง แล้วก็วนกลับไป random เป้าหมายใหม่จนครบ 40 ดังข้อ3

## Reference
1. Main Research Paper
    - [A Benchmark Dataset for SSVEP-Based Brain-Computer Interfaces](https://www.researchgate.net/publication/309897862_A_Benchmark_Dataset_for_SSVEP-Based_Brain-Computer_Interfaces)
2. CCA Implementation:
    - [Combining the Benefits of CCA and SVMs for SSVEP-based BCIs in Real-world Conditions](https://www.researchgate.net/publication/320572057_Combining_the_Benefits_of_CCA_and_SVMs_for_SSVEP-based_BCIs_in_Real-world_Conditions/download)
    - https://stats.stackexchange.com/questions/77287/canonical-correlation-analysis-without-raw-data-algebra-of-cca/77309#77309
    - https://stats.stackexchange.com/questions/65692/how-to-visualize-what-canonical-correlation-analysis-does-in-comparison-to-what
3. How to solve for Maximum Canonical Correlation
    - [A Tutorial on Canonical Correlation Methods](https://arxiv.org/abs/1711.02391)
4. Best Electrodes to use
    - [An online multi-channel SSVEP-based brain-computer interface using a canonical correlation analysis method.](https://www.ncbi.nlm.nih.gov/pubmed/19494422)

In [1]:
%matplotlib inline

In [2]:
%%javascript
// Disable scroll bar
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [2]:
!pip install xarray

Collecting xarray
  Downloading xarray-2025.1.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24 in c:\users\qianqian\appdata\local\programs\python\python312\lib\site-packages (from xarray) (1.26.4)
Requirement already satisfied: packaging>=23.2 in c:\users\qianqian\appdata\local\programs\python\python312\lib\site-packages (from xarray) (24.1)
Requirement already satisfied: pandas>=2.1 in c:\users\qianqian\appdata\local\programs\python\python312\lib\site-packages (from xarray) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\qianqian\appdata\local\programs\python\python312\lib\site-packages (from pandas>=2.1->xarray) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\qianqian\appdata\local\programs\python\python312\lib\site-packages (from pandas>=2.1->xarray) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\qianqian\appdata\local\programs\python\python312\lib\site-packages (from pandas>=2.1->xarray) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\qianqian\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1->xarray) (1.16.0)
Downloading xarray-2025.1.2-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB 991.0 kB/s eta 0:00:02
   ---------- ----------------------------- 0.3/1.2 MB 4.1 MB/s eta 0:00:01
   --------------------- ------------------ 0.7/1.2 MB 5.4 MB/s eta 0:00:01
   -------------------------------- ------- 1.0/1.2 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 6.1 MB/s eta 0:00:00
Installing collected packages: xarray
Successfully installed xarray-2025.1.2

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Imports

In [82]:
import scipy.io
from scipy.signal import butter, lfilter
import pandas as pd
import xarray as xr
import numpy as np
from pprint import pprint
from functools import reduce
import re
from matplotlib import pyplot as plt
from IPython.display import display, Markdown

# Parameters

In [57]:
# Parameters for Benchmark dataset
fs = 250
n_targets = 10
t_cue = 0.5
n_trials = 6
t_select = 1

# Parameters for Butterworth filter
lowcut = 7
highcut = 40

# Parater for CCA classification
n_harmonics = 6
PI = np.pi

# an index of time frame after 0.5s * 250Hz has passed
post_stimulus_time_index = int(t_cue * fs) # SSVEP 开始前的提示信号

# Functions

In [58]:
# 从多维数组中提取当前频率、当前次实验中每个电极的数据
def get_input_data(raw_data, electrodes, target_id, block_id):
    interest_electrode_ids = []
    for electrode in electrodes:
        interest_electrode_ids.append(elec_to_elec_id_map[electrode])
    result = {}
    for electrode_id in interest_electrode_ids:
        values = []
        for t in range(len(raw_data[electrode_id])):
            values.append(raw_data[electrode_id][t][target_id][block_id])
        result[elec_id_to_elec_map[electrode_id]] = values
    return result

In [59]:
def bandpass_filter(data, lowcut, highcut, fs, order=5):
    nyq  = 0.5 * fs  # Nyquist Frequency
    low  = lowcut / nyq
    high = highcut /nyq
    b, a = butter(order, [low, high], btype='band')
    y    = lfilter(b, a, data)

In [60]:
# 所有谐波相加得到参考信号中 t 时刻的信号采样点
def generate_reference_signal_at_time(f, t, max_harmonic, phase):
    values = []
    for h in range(1, max_harmonic + 1):
        values += ref_wave(f, h, t, phase)
    return values

def generate_reference_signal(frequency, sampling_frequency, total_time, max_harmonic, phase):
    ref_signal = []
    num_time_step = int(total_time * sampling_frequency)
    for step in range(num_time_step):
        time = step * 1/sampling_frequency
        ref_signal_at_t = generate_reference_signal_at_time(frequency, time, max_harmonic, phase)
        ref_signal.append(ref_signal_at_t)
    return ref_signal

In [61]:
def find_maximum_canonical_correlations(X, Y):
    if X.shape[0] == Y.shape[0]:
        N = X.shape[0]
    else:
        print('time frame is not equal')
        return None
    C_xx = 1/N * (X.T @ X) # X 自相关
    C_yy = 1/N * (Y.T @ Y) # Y 自相关
    C_xy = 1/N * (X.T @ Y) # X, Y 互相关
    C_yx = 1/N * (Y.T @ X)
    C_xx_inv = np.linalg.pinv(C_xx) # X 自相关的逆矩阵
    C_yy_inv = np.linalg.pinv(C_yy)
    eig_values, eig_vectors = scipy.linalg.eig(C_yy_inv @ C_yx @ C_xx_inv @ C_xy)
    sqrt_eig_values = np.sqrt(eig_values)
    return max(sqrt_eig_values)

# Load data

In [62]:
# Map electrode names to thier index for easier read/use
f = open("D:/2024/7-9/dissertation/code/64-channels.loc", "r")
lines = re.split('\n', f.read())
electrodes = [] #二维列表
for line in lines:
    electrodes.append(list(filter(lambda text: len(text) > 0, re.split('\s', line)))) # 去除每行分割后的空元素
electrodes = list(filter(lambda l: len(l) > 0, electrodes)) #去除空白的行

#建立电极名称和电极ID的相互映射
elec_to_elec_id_map = {}
elec_id_to_elec_map = {}
for i in range(len(electrodes)):
    elec_to_elec_id_map[electrodes[i][3]] = int(electrodes[i][0])
    elec_id_to_elec_map[int(electrodes[i][0])] = electrodes[i][3]

<>:6: SyntaxWarning: invalid escape sequence '\s'
<>:6: SyntaxWarning: invalid escape sequence '\s'
C:\Users\qianqian\AppData\Local\Temp\ipykernel_3672\3885769207.py:6: SyntaxWarning: invalid escape sequence '\s'
  electrodes.append(list(filter(lambda text: len(text) > 0, re.split('\s', line)))) # 去除每行分割后的空元素

In [63]:
# from ftp://sccn.ucsd.edu/pub/ssvep_benchmark_dataset/
main_data_file = 'D:/2024/7-9/dissertation/code/S1.mat' #仅研究第一个受试者

In [64]:
mat = scipy.io.loadmat(main_data_file)
raw_data = mat['data'] # (channels, samples, targets, trials)

In [65]:
# print(raw_data.shape[1])

In [66]:
target_setting_info = scipy.io.loadmat('D:/2024/7-9/dissertation/code/Freq_Phase.mat')

In [67]:
# 2列数据，1列存储频率，1列存储相位
target_setting = pd.DataFrame.from_dict({
    "frequency": target_setting_info['freqs'][0], # 8, 9, ..., 15, 8.2, 9.2, ..., 15.2, ..., 8.8, 9.8, ..., 15.8 Hz
    "phase": target_setting_info['phases'][0]
})

## Reformat SSVEP data into DataFrame

In [68]:
# Chosen from Reference Paper #4
interest_channels = ['P3', 'PZ', 'P4', 'PO7', 'POz', 'O1', 'Oz', 'O2', 'PO8']
# 10 out of 40 
target_ids = range(n_targets) #选择前 10 个频率进行分类 (8, 9, ..., 15, 8.2, 9.2 Hz) -- (0, 1, ..., 9)
trial_ids = range(n_trials) # trials

In [91]:
X = {} # 最终结构 (target, trial, channel, sample)
for target_id in target_ids:
    if target_id not in X:
        X[target_id] = {} #如果 target_id 不存在于字典 X 中，为其初始化一个空字典
    for trial_id in trial_ids:
        if trial_id not in X[target_id]:
            X[target_id][trial_id] = {}
        
        X[target_id][trial_id] = pd.DataFrame.from_dict(
            get_input_data(raw_data, interest_channels, target_id, trial_id)
        )[post_stimulus_time_index:post_stimulus_time_index+t_select*fs] # 数据段从提示信号结束之后开始

ValueError: selected axis is out of range

In [89]:
 X[target_ids[0]][trial_ids[0]].head() # 返回第一个频率，第一次实验数据中所有通道的前 5 个采样值
# X[target_ids[0]][trial_ids[0]].shape

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [29]:
'''
print('channel:', interest_channels[0])
print('number of data points:', len(X[target_ids[0]][trial_ids[0]][interest_channels[0]]))
plt.plot(X[target_ids[0]][trial_ids[0]][interest_channels[0]])
'''

"\nprint('channel:', interest_channels[0])\nprint('number of data points:', len(X[target_ids[0]][trial_ids[0]][interest_channels[0]]))\nplt.plot(X[target_ids[0]][trial_ids[0]][interest_channels[0]])\n"

## Generate Reference Signal

In [36]:
sin = lambda f, h, t, p: np.sin(2*PI*f*h*t + p) # 定义正弦函数
cos = lambda f, h, t, p: np.cos(2*PI*f*h*t + p)
ref_wave = lambda f, h, t, p: [sin(f, h, t, p), cos(f, h, t, p)]

In [41]:
Y = {}
for setting_index in target_setting.index:
    frequency, phase = target_setting.iloc[setting_index] # 提取每个频率和相位
    signal = generate_reference_signal(
        frequency = frequency,
        sampling_frequency = fs,
        total_time = t_cue + t_select,
        max_harmonic = n_harmonics,
        phase = phase
    )
    Y[f'setting_{setting_index}'] = pd.DataFrame(signal[post_stimulus_time_index:])

In [42]:
# columns are [sin, cos] * [number of harmonic] (2 * 6 = 12)
# rows are time steps
# Example Reference Signal
# Y['setting_0'].head()
# Y['setting_0'].shape

In [43]:
# plt.plot(Y['setting_0'][0])

## Optimization to find max ρ (canonial correlation)

In [48]:
result = {}
# X[target_id][block_id]
for target_id in target_ids:
    if target_id not in result:
        result[target_id] = {}
    for trial_id in trial_ids:
        if trial_id not in result[target_id]:
            result[target_id][trial_id] = {}
        keys = list(Y.keys()) # [cos, sin] * [harmonics] (0 - 11)
        for ref_signal_id in keys:
            value = find_maximum_canonical_correlations(
                X = X[target_id][trial_id].values,
                Y = Y[ref_signal_id].values
            )
            if value.imag == 0.0:
                result[target_id][trial_id][ref_signal_id] = value.real
            else:
                result[target_id][trial_id][ref_signal_id] = None

## Classification & Accuracy of the algorithm

In [52]:
for target_id in target_ids:
    display(Markdown(f"## Target: {target_id}"))
    df = pd.DataFrame.from_dict(result[target_id])
    display(Markdown('### Classification:'))
    num_correct= 0
    for trial_id in trial_ids:
        _, top_correlation_setting = df[trial_id].idxmax().split('_')
        is_correct = int(top_correlation_setting) == target_id
        if is_correct:
            num_correct += 1
        display(
            Markdown(f'Trial #{trial_id} Correct output should be {target_id}, classify as {top_correlation_setting}: **{is_correct}**')
        )
    display(
        Markdown('Accuracy: **%.2f%%**'%(num_correct/len(trial_ids)*100))
    )
    display(Markdown('### Raw Max CC Value (rows are blocks)'))
    display(df)

## Target: 0

### Classification:

Block #0 Correct output should be 0, classify as 0: **True**

Block #1 Correct output should be 0, classify as 26: **False**

Block #2 Correct output should be 0, classify as 21: **False**

Block #3 Correct output should be 0, classify as 20: **False**

Block #4 Correct output should be 0, classify as 34: **False**

Block #5 Correct output should be 0, classify as 19: **False**

Accuracy: **16.67%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.634772  0.441479  0.493871  0.479300  0.560266  0.440713
setting_1   0.381060  0.417961  0.439204  0.541807  0.346221  0.341992
setting_2   0.539640  0.405976  0.387442  0.415393  0.478333  0.387572
setting_3   0.453809  0.435895  0.407330  0.408918  0.598022  0.417928
setting_4   0.437267  0.435134  0.456342  0.543793  0.452713  0.452204
setting_5   0.378774  0.377775  0.431819  0.452727  0.422622  0.307172
setting_6   0.356900  0.355342  0.380831  0.476843  0.286479  0.419113
setting_7   0.419780  0.311713  0.272788  0.342014  0.330721  0.335450
setting_8   0.624046  0.447227  0.504859  0.345740  0.528464  0.405386
setting_9   0.420851  0.443681  0.400589  0.503138  0.408816  0.352479
setting_10  0.502372  0.476262  0.361811  0.477399  0.428059  0.425520
setting_11  0.483840  0.509199  0.409000  0.415779  0.567590  0.483827
setting_12  0.461033  0.440290  0.413494  0.527154  0.411611  0.478476
setting_13  0.360780  0.279519  0.477900  0.496005  0.455245  0.320784
setting_14  0.328089  0.358450  0.343612  0.409844  0.301255  0.371325
setting_15  0.405627  0.328496  0.321899  0.333712  0.363280  0.329265
setting_16  0.595421  0.417528  0.476813  0.410744  0.471460  0.364197
setting_17  0.420203  0.451662  0.452219  0.427559  0.490704  0.388353
setting_18  0.439876  0.486432  0.346705  0.538670  0.434271  0.429532
setting_19  0.490333  0.508523  0.389330  0.387910  0.504337  0.520991
setting_20  0.495505  0.474087  0.326298  0.550345  0.419016  0.463743
setting_21  0.348039  0.315351  0.534439  0.477126  0.413887  0.382577
setting_22  0.384566  0.324550  0.342695  0.433456  0.339867  0.366017
setting_23  0.406997  0.350394  0.397125  0.361022  0.395510  0.317456
setting_24  0.584277  0.398853  0.443982  0.472668  0.398796  0.343579
setting_25  0.481855  0.435052  0.461296  0.396479  0.532024  0.381076
setting_26  0.365571  0.512617  0.409940  0.539411  0.529791  0.383941
setting_27  0.473789  0.487734  0.437665  0.413971  0.447852  0.514831
setting_28  0.498677  0.464015  0.327090  0.485645  0.420949  0.414364
setting_29  0.368014  0.325472  0.530200  0.399394  0.351500  0.421489
setting_30  0.426350  0.328371  0.318458  0.436309  0.354740  0.372014
setting_31  0.495556  0.327633  0.457181  0.415701  0.387807  0.289578
setting_32  0.453598  0.417250  0.423472  0.514275  0.409286  0.291817
setting_33  0.528327  0.401535  0.454094  0.440748  0.507657  0.363044
setting_34  0.373184  0.463964  0.401090  0.468274  0.603391  0.377108
setting_35  0.458325  0.463338  0.458881  0.493908  0.463674  0.485642
setting_36  0.446634  0.427884  0.374067  0.414443  0.402689  0.353078
setting_37  0.379193  0.347217  0.456746  0.428385  0.329658  0.428255
setting_38  0.426350  0.380939  0.307972  0.405867  0.334915  0.370228
setting_39  0.557152  0.364066  0.471420  0.453412  0.422483  0.345657

## Target: 1

### Classification:

Block #0 Correct output should be 1, classify as 19: **False**

Block #1 Correct output should be 1, classify as 9: **False**

Block #2 Correct output should be 1, classify as 8: **False**

Block #3 Correct output should be 1, classify as 16: **False**

Block #4 Correct output should be 1, classify as 34: **False**

Block #5 Correct output should be 1, classify as 0: **False**

Accuracy: **0.00%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.518004  0.314297  0.605661  0.377233  0.356301  0.511705
setting_1   0.504011  0.468090  0.552523  0.367747  0.472571  0.420806
setting_2   0.447798  0.417296  0.333088  0.398153  0.492678  0.330587
setting_3   0.655768  0.378252  0.526167  0.451159  0.690996  0.295379
setting_4   0.599705  0.406848  0.441563  0.324518  0.400678  0.453668
setting_5   0.333267  0.417198  0.610610  0.265322  0.349147  0.378304
setting_6   0.483859  0.389492  0.373655  0.356565  0.337237  0.433328
setting_7   0.416346  0.430591  0.414623  0.301668  0.358273  0.396600
setting_8   0.502307  0.368187  0.634759  0.447652  0.338513  0.480070
setting_9   0.500110  0.485942  0.471371  0.373785  0.461156  0.419906
setting_10  0.418494  0.407206  0.330630  0.434674  0.543404  0.273408
setting_11  0.723357  0.409880  0.548872  0.438647  0.599049  0.306720
setting_12  0.527253  0.416813  0.399694  0.308466  0.411168  0.427461
setting_13  0.372259  0.405545  0.574952  0.298017  0.337058  0.377476
setting_14  0.511123  0.384769  0.468370  0.285807  0.392746  0.469510
setting_15  0.378125  0.436290  0.413516  0.324660  0.332807  0.335095
setting_16  0.511381  0.411496  0.622200  0.474683  0.434476  0.468522
setting_17  0.479980  0.384548  0.394355  0.336632  0.427196  0.406238
setting_18  0.485858  0.416759  0.347858  0.440555  0.620065  0.335500
setting_19  0.728344  0.387187  0.542250  0.425377  0.491741  0.374481
setting_20  0.440155  0.398913  0.405325  0.287762  0.399067  0.404281
setting_21  0.371230  0.418292  0.488340  0.362392  0.325228  0.363362
setting_22  0.527345  0.350320  0.507869  0.287070  0.426445  0.430851
setting_23  0.407089  0.405105  0.468102  0.296854  0.347152  0.321579
setting_24  0.506774  0.393874  0.593696  0.463145  0.463397  0.446629
setting_25  0.451386  0.413306  0.349699  0.290725  0.443907  0.322191
setting_26  0.556885  0.413995  0.377940  0.355735  0.704171  0.406473
setting_27  0.702197  0.401081  0.524250  0.410067  0.426884  0.398354
setting_28  0.376595  0.406636  0.506062  0.259468  0.330007  0.359041
setting_29  0.395847  0.439326  0.399643  0.396716  0.314983  0.368266
setting_30  0.542840  0.327155  0.500325  0.265752  0.415155  0.419655
setting_31  0.379247  0.334401  0.511432  0.288489  0.409026  0.360844
setting_32  0.501098  0.379284  0.574507  0.426901  0.436623  0.441919
setting_33  0.484553  0.442223  0.374227  0.323652  0.452296  0.303085
setting_34  0.590026  0.391206  0.478873  0.393488  0.740140  0.311434
setting_35  0.654106  0.402314  0.475349  0.332387  0.380053  0.445421
setting_36  0.332578  0.388247  0.585676  0.268542  0.335015  0.353062
setting_37  0.447957  0.399771  0.366812  0.406448  0.293289  0.397566
setting_38  0.486334  0.386789  0.455306  0.266857  0.383341  0.383324
setting_39  0.395591  0.270553  0.502192  0.271973  0.426784  0.378408

## Target: 2

### Classification:

Block #0 Correct output should be 2, classify as 18: **False**

Block #1 Correct output should be 2, classify as 10: **False**

Block #2 Correct output should be 2, classify as 33: **False**

Block #3 Correct output should be 2, classify as 2: **True**

Block #4 Correct output should be 2, classify as 2: **True**

Block #5 Correct output should be 2, classify as 2: **True**

Accuracy: **50.00%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.438597  0.386408  0.397093  0.404139  0.383962  0.458662
setting_1   0.554043  0.363705  0.434879  0.602189  0.398631  0.358834
setting_2   0.612367  0.630712  0.496494  0.696218  0.729185  0.633203
setting_3   0.436332  0.443775  0.404664  0.465282  0.560578  0.509538
setting_4   0.405676  0.570427  0.380008  0.402120  0.383434  0.413657
setting_5   0.455193  0.359877  0.406455  0.376901  0.356342  0.380333
setting_6   0.395046  0.357606  0.358324  0.437353  0.401336  0.327100
setting_7   0.333681  0.302347  0.331439  0.374847  0.371804  0.379289
setting_8   0.453329  0.379154  0.441785  0.396458  0.441885  0.431306
setting_9   0.614793  0.383890  0.367451  0.613616  0.448375  0.430144
setting_10  0.707259  0.661162  0.431090  0.695652  0.691911  0.599189
setting_11  0.392619  0.440385  0.386157  0.486376  0.459159  0.430545
setting_12  0.367579  0.580133  0.317807  0.378772  0.387651  0.374098
setting_13  0.431477  0.370191  0.388864  0.341728  0.324024  0.343276
setting_14  0.353049  0.341176  0.346221  0.482566  0.381219  0.326679
setting_15  0.381238  0.296857  0.284305  0.389992  0.410084  0.317548
setting_16  0.479155  0.365905  0.488478  0.422310  0.362265  0.360725
setting_17  0.618548  0.360313  0.366834  0.622883  0.521358  0.501727
setting_18  0.746932  0.634243  0.324259  0.647958  0.685147  0.604381
setting_19  0.350006  0.476279  0.370929  0.507757  0.385076  0.361655
setting_20  0.375540  0.564179  0.352775  0.394368  0.424080  0.357222
setting_21  0.367662  0.364381  0.346870  0.294378  0.320612  0.366739
setting_22  0.336971  0.321253  0.305184  0.513922  0.349700  0.356723
setting_23  0.376000  0.310857  0.268571  0.334402  0.369891  0.281802
setting_24  0.510427  0.353045  0.450436  0.500566  0.420162  0.370802
setting_25  0.568093  0.459206  0.460062  0.649157  0.626760  0.496829
setting_26  0.678017  0.560029  0.371415  0.580593  0.696691  0.610476
setting_27  0.342760  0.500552  0.338426  0.467507  0.287132  0.373038
setting_28  0.405370  0.531730  0.348801  0.390644  0.417724  0.344812
setting_29  0.356002  0.339258  0.348413  0.307866  0.326605  0.366962
setting_30  0.268632  0.325189  0.287094  0.472329  0.297789  0.369423
setting_31  0.318027  0.260247  0.312052  0.365849  0.267532  0.285737
setting_32  0.522553  0.322028  0.464504  0.569120  0.441001  0.344183
setting_33  0.525083  0.572034  0.507850  0.671487  0.703725  0.583882
setting_34  0.549089  0.480095  0.367085  0.499469  0.653088  0.574181
setting_35  0.402756  0.537527  0.342898  0.452266  0.367275  0.416126
setting_36  0.381964  0.448742  0.396641  0.397327  0.382221  0.360599
setting_37  0.415996  0.286135  0.344175  0.369497  0.401905  0.341187
setting_38  0.313763  0.296216  0.321114  0.429315  0.306210  0.372527
setting_39  0.273654  0.310496  0.304563  0.327660  0.314966  0.294630

## Target: 3

### Classification:

Block #0 Correct output should be 3, classify as 3: **True**

Block #1 Correct output should be 3, classify as 3: **True**

Block #2 Correct output should be 3, classify as 3: **True**

Block #3 Correct output should be 3, classify as 3: **True**

Block #4 Correct output should be 3, classify as 18: **False**

Block #5 Correct output should be 3, classify as 3: **True**

Accuracy: **83.33%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.360788  0.400105  0.323443  0.440691  0.422838  0.477719
setting_1   0.441974  0.404564  0.312868  0.436495  0.388640  0.407357
setting_2   0.586354  0.425611  0.561614  0.430278  0.464600  0.374570
setting_3   0.742389  0.561969  0.616676  0.716346  0.440045  0.637883
setting_4   0.461866  0.485931  0.391867  0.472344  0.496534  0.379785
setting_5   0.394454  0.471193  0.438812  0.322871  0.454605  0.353566
setting_6   0.429878  0.378902  0.449304  0.289401  0.358657  0.433696
setting_7   0.280952  0.290433  0.285671  0.343489  0.284276  0.344212
setting_8   0.339384  0.390585  0.373223  0.435258  0.347798  0.457586
setting_9   0.432903  0.369315  0.391016  0.427577  0.366456  0.344008
setting_10  0.640911  0.455709  0.461492  0.467871  0.543990  0.415628
setting_11  0.692731  0.535892  0.575449  0.656473  0.428494  0.586925
setting_12  0.514712  0.477465  0.409293  0.492696  0.467697  0.401419
setting_13  0.390566  0.424425  0.482030  0.368157  0.389860  0.346456
setting_14  0.382373  0.358711  0.393475  0.235289  0.420923  0.376809
setting_15  0.279010  0.272347  0.273416  0.297403  0.262950  0.355380
setting_16  0.403551  0.370152  0.411580  0.372800  0.390597  0.423657
setting_17  0.455627  0.394394  0.449212  0.363153  0.422462  0.321902
setting_18  0.658274  0.453857  0.322876  0.546439  0.556617  0.445499
setting_19  0.571585  0.529720  0.571518  0.559707  0.408696  0.464213
setting_20  0.524692  0.476335  0.432970  0.433094  0.445710  0.367324
setting_21  0.369303  0.405524  0.517118  0.377874  0.331076  0.326439
setting_22  0.389415  0.364257  0.385073  0.300324  0.376079  0.330804
setting_23  0.266947  0.374549  0.320389  0.260771  0.312732  0.359599
setting_24  0.378167  0.469688  0.388825  0.427037  0.334387  0.462923
setting_25  0.488333  0.460244  0.534507  0.356410  0.461728  0.338129
setting_26  0.631316  0.491976  0.415073  0.611062  0.491839  0.475160
setting_27  0.461797  0.548343  0.526692  0.471539  0.413734  0.429926
setting_28  0.492157  0.422517  0.400562  0.435800  0.452112  0.360692
setting_29  0.402811  0.304674  0.500255  0.360911  0.320777  0.349969
setting_30  0.319878  0.343423  0.351762  0.288891  0.376388  0.284281
setting_31  0.354699  0.342722  0.303011  0.300494  0.332268  0.377349
setting_32  0.433594  0.396596  0.384680  0.417186  0.343684  0.437768
setting_33  0.546031  0.445245  0.586941  0.401689  0.395501  0.331428
setting_34  0.710249  0.531621  0.544102  0.668944  0.431248  0.560713
setting_35  0.464862  0.526686  0.433389  0.447033  0.449607  0.411308
setting_36  0.426869  0.446319  0.396242  0.389702  0.479433  0.317951
setting_37  0.446170  0.300460  0.468798  0.329609  0.353871  0.420603
setting_38  0.316694  0.326364  0.354618  0.336807  0.319716  0.325658
setting_39  0.300780  0.270034  0.308878  0.332094  0.365560  0.355103

## Target: 4

### Classification:

Block #0 Correct output should be 4, classify as 12: **False**

Block #1 Correct output should be 4, classify as 21: **False**

Block #2 Correct output should be 4, classify as 2: **False**

Block #3 Correct output should be 4, classify as 12: **False**

Block #4 Correct output should be 4, classify as 14: **False**

Block #5 Correct output should be 4, classify as 12: **False**

Accuracy: **0.00%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.331915  0.469100  0.427394  0.410087  0.454832  0.458780
setting_1   0.383080  0.465069  0.317193  0.324690  0.338734  0.475712
setting_2   0.408286  0.401180  0.575093  0.312703  0.429800  0.520378
setting_3   0.623599  0.421949  0.396254  0.610161  0.327754  0.554373
setting_4   0.642652  0.524277  0.512535  0.646204  0.538666  0.614145
setting_5   0.517843  0.525152  0.365431  0.447020  0.515366  0.446459
setting_6   0.399217  0.462320  0.397529  0.395740  0.629168  0.393881
setting_7   0.376730  0.328833  0.413534  0.328043  0.335229  0.370568
setting_8   0.351307  0.502071  0.404382  0.417206  0.423658  0.497247
setting_9   0.381330  0.474206  0.312704  0.340496  0.342939  0.428290
setting_10  0.407463  0.402320  0.574372  0.330565  0.407229  0.490721
setting_11  0.584327  0.537367  0.286707  0.677402  0.379999  0.553227
setting_12  0.685243  0.508961  0.570216  0.679303  0.618082  0.621341
setting_13  0.561591  0.578514  0.319248  0.472435  0.511868  0.362495
setting_14  0.366436  0.365807  0.434060  0.351160  0.645494  0.361336
setting_15  0.356210  0.298511  0.423566  0.336960  0.319681  0.362052
setting_16  0.309456  0.552333  0.400298  0.371357  0.430936  0.463311
setting_17  0.408566  0.450516  0.394987  0.345228  0.362643  0.456622
setting_18  0.461846  0.407998  0.560235  0.346165  0.339185  0.490477
setting_19  0.531573  0.594328  0.274848  0.670522  0.445485  0.549786
setting_20  0.621948  0.508144  0.569746  0.666149  0.607318  0.576363
setting_21  0.567540  0.613746  0.323159  0.498799  0.509020  0.428060
setting_22  0.327405  0.349371  0.446212  0.344846  0.622107  0.336346
setting_23  0.331114  0.328133  0.391967  0.389679  0.251898  0.310086
setting_24  0.323467  0.497417  0.408213  0.408592  0.412096  0.451420
setting_25  0.430325  0.412042  0.475550  0.382926  0.403330  0.538778
setting_26  0.561201  0.398131  0.540418  0.401880  0.324439  0.523956
setting_27  0.515302  0.558913  0.334536  0.606978  0.450185  0.577148
setting_28  0.551766  0.450941  0.527662  0.620290  0.575051  0.515536
setting_29  0.521107  0.596789  0.361117  0.491501  0.542667  0.456419
setting_30  0.320411  0.316630  0.405590  0.315026  0.553560  0.355487
setting_31  0.292860  0.307588  0.379658  0.380809  0.301546  0.313892
setting_32  0.379679  0.434151  0.365831  0.358741  0.365939  0.430154
setting_33  0.388510  0.401223  0.539567  0.385577  0.407916  0.547660
setting_34  0.612462  0.421401  0.494265  0.497985  0.279856  0.537287
setting_35  0.555128  0.498449  0.415110  0.595737  0.433938  0.578647
setting_36  0.505693  0.465668  0.462782  0.535305  0.528481  0.483935
setting_37  0.465895  0.536677  0.384379  0.467334  0.595551  0.444708
setting_38  0.373055  0.284744  0.399916  0.322026  0.433369  0.361018
setting_39  0.240137  0.311626  0.363490  0.292488  0.303835  0.345964

## Target: 5

### Classification:

Block #0 Correct output should be 5, classify as 8: **False**

Block #1 Correct output should be 5, classify as 20: **False**

Block #2 Correct output should be 5, classify as 33: **False**

Block #3 Correct output should be 5, classify as 6: **False**

Block #4 Correct output should be 5, classify as 10: **False**

Block #5 Correct output should be 5, classify as 32: **False**

Accuracy: **0.00%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.416451  0.375288  0.382512  0.372380  0.454033  0.410327
setting_1   0.416283  0.569586  0.523288  0.412938  0.371838  0.581535
setting_2   0.378027  0.468262  0.503545  0.376934  0.584708  0.425185
setting_3   0.445870  0.599972  0.554337  0.455489  0.391592  0.482430
setting_4   0.355281  0.549149  0.462182  0.387443  0.564000  0.585721
setting_5   0.388402  0.479966  0.527988  0.456950  0.575100  0.501593
setting_6   0.352654  0.371793  0.374964  0.562986  0.372857  0.390417
setting_7   0.334061  0.314697  0.397012  0.410746  0.405326  0.355828
setting_8   0.529348  0.372955  0.409250  0.361118  0.363419  0.466195
setting_9   0.360316  0.561348  0.509165  0.446305  0.372167  0.500479
setting_10  0.383884  0.426075  0.431832  0.370966  0.598829  0.491821
setting_11  0.519166  0.547071  0.495523  0.432575  0.403296  0.511117
setting_12  0.387301  0.586984  0.526459  0.464758  0.507682  0.562054
setting_13  0.309103  0.417582  0.478049  0.417697  0.549834  0.471797
setting_14  0.380198  0.293531  0.344749  0.561732  0.393260  0.352587
setting_15  0.338367  0.280824  0.361161  0.340290  0.348218  0.335117
setting_16  0.523079  0.430727  0.438293  0.332108  0.385329  0.538544
setting_17  0.390747  0.528273  0.565500  0.444096  0.422389  0.457265
setting_18  0.370364  0.421668  0.429102  0.360297  0.583362  0.503198
setting_19  0.503340  0.496951  0.437289  0.345793  0.438374  0.560594
setting_20  0.428326  0.648890  0.572652  0.531001  0.425576  0.531980
setting_21  0.298490  0.426276  0.394415  0.397168  0.485032  0.427010
setting_22  0.383659  0.265580  0.389239  0.528657  0.402742  0.332355
setting_23  0.314943  0.292410  0.338055  0.304952  0.327404  0.307821
setting_24  0.488166  0.494182  0.479135  0.336544  0.374247  0.592198
setting_25  0.384795  0.529477  0.589554  0.412910  0.399802  0.400345
setting_26  0.377915  0.481413  0.520072  0.392604  0.539525  0.482650
setting_27  0.493418  0.476796  0.428524  0.356459  0.500708  0.608956
setting_28  0.405782  0.639015  0.586221  0.533543  0.504130  0.543890
setting_29  0.324739  0.440294  0.398890  0.395512  0.435885  0.421774
setting_30  0.338090  0.288652  0.384124  0.481604  0.441013  0.341911
setting_31  0.298701  0.315254  0.342071  0.297071  0.324281  0.328048
setting_32  0.428508  0.532704  0.488062  0.371473  0.375321  0.617281
setting_33  0.367409  0.518542  0.596871  0.391600  0.516239  0.386294
setting_34  0.362923  0.566344  0.562128  0.426708  0.432820  0.483712
setting_35  0.426837  0.497802  0.432702  0.340798  0.577600  0.614760
setting_36  0.412950  0.561184  0.551676  0.488668  0.544235  0.531870
setting_37  0.292655  0.415447  0.400019  0.502292  0.395200  0.406528
setting_38  0.338054  0.284445  0.396409  0.435669  0.439254  0.355465
setting_39  0.299901  0.296425  0.411555  0.349506  0.326151  0.289279

## Target: 6

### Classification:

Block #0 Correct output should be 6, classify as 29: **False**

Block #1 Correct output should be 6, classify as 10: **False**

Block #2 Correct output should be 6, classify as 4: **False**

Block #3 Correct output should be 6, classify as 14: **False**

Block #4 Correct output should be 6, classify as 27: **False**

Block #5 Correct output should be 6, classify as 13: **False**

Accuracy: **0.00%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.394096  0.476096  0.456022  0.392317  0.545417  0.414030
setting_1   0.486635  0.395141  0.420387  0.359732  0.401158  0.438896
setting_2   0.310601  0.509230  0.392797  0.418075  0.412649  0.444045
setting_3   0.478333  0.330779  0.397839  0.459875  0.629250  0.461257
setting_4   0.471999  0.447210  0.696801  0.356766  0.589177  0.327455
setting_5   0.464995  0.419915  0.455136  0.426848  0.495536  0.497716
setting_6   0.560512  0.397397  0.466489  0.640856  0.482931  0.326876
setting_7   0.347798  0.386431  0.321453  0.339197  0.425753  0.349644
setting_8   0.444054  0.442911  0.392960  0.454458  0.438354  0.411840
setting_9   0.462225  0.385785  0.411265  0.338192  0.466724  0.454712
setting_10  0.379785  0.530776  0.356512  0.377963  0.485745  0.430425
setting_11  0.437382  0.270657  0.477985  0.391693  0.624233  0.459348
setting_12  0.484045  0.459575  0.679667  0.425205  0.581541  0.330359
setting_13  0.535115  0.448103  0.481825  0.404486  0.523780  0.517705
setting_14  0.439502  0.346935  0.452286  0.661117  0.472449  0.341361
setting_15  0.363736  0.436415  0.274947  0.298940  0.399540  0.271403
setting_16  0.385222  0.415784  0.397811  0.436556  0.375066  0.419241
setting_17  0.419204  0.429849  0.443912  0.345060  0.497676  0.419840
setting_18  0.453384  0.526251  0.341023  0.395040  0.569971  0.439059
setting_19  0.402400  0.299386  0.573380  0.349982  0.633285  0.458766
setting_20  0.469842  0.422049  0.635085  0.492619  0.616921  0.335069
setting_21  0.635794  0.396533  0.532617  0.443989  0.528929  0.449076
setting_22  0.328457  0.289390  0.419710  0.627345  0.444159  0.366003
setting_23  0.327309  0.453229  0.246237  0.336798  0.386366  0.268542
setting_24  0.498452  0.370075  0.434536  0.409380  0.391142  0.467835
setting_25  0.380466  0.485138  0.378652  0.359155  0.459514  0.444602
setting_26  0.498441  0.507279  0.340637  0.383360  0.619182  0.361086
setting_27  0.427600  0.363276  0.643829  0.317185  0.653006  0.408885
setting_28  0.468992  0.377475  0.561388  0.513335  0.602619  0.399158
setting_29  0.675565  0.395403  0.509342  0.552389  0.531535  0.351744
setting_30  0.265232  0.296301  0.413039  0.545789  0.409010  0.341684
setting_31  0.331775  0.457258  0.265598  0.299689  0.383613  0.249155
setting_32  0.503280  0.403874  0.404189  0.368035  0.394610  0.464307
setting_33  0.352921  0.528412  0.402715  0.405934  0.396233  0.409541
setting_34  0.478290  0.420996  0.341658  0.441542  0.623688  0.421150
setting_35  0.463229  0.389365  0.694584  0.362230  0.642850  0.331281
setting_36  0.446105  0.400177  0.509998  0.491511  0.534595  0.452466
setting_37  0.649790  0.410380  0.461298  0.596019  0.506398  0.359837
setting_38  0.296513  0.355680  0.371482  0.420481  0.409611  0.322906
setting_39  0.328761  0.447278  0.346486  0.344039  0.392364  0.310753

## Target: 7

### Classification:

Block #0 Correct output should be 7, classify as 27: **False**

Block #1 Correct output should be 7, classify as 37: **False**

Block #2 Correct output should be 7, classify as 38: **False**

Block #3 Correct output should be 7, classify as 12: **False**

Block #4 Correct output should be 7, classify as 5: **False**

Block #5 Correct output should be 7, classify as 34: **False**

Accuracy: **0.00%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.539381  0.450249  0.452824  0.385307  0.449658  0.404619
setting_1   0.431091  0.404206  0.385157  0.454903  0.409390  0.422667
setting_2   0.413180  0.345422  0.299684  0.300712  0.327881  0.432853
setting_3   0.448518  0.364410  0.354708  0.541151  0.326561  0.499800
setting_4   0.528564  0.382035  0.448773  0.634616  0.457053  0.482244
setting_5   0.421254  0.376522  0.381364  0.527321  0.731665  0.398085
setting_6   0.321439  0.545509  0.375229  0.347220  0.333264  0.436327
setting_7   0.488139  0.421287  0.447735  0.559579  0.523408  0.528561
setting_8   0.582613  0.392988  0.376876  0.399290  0.339112  0.330498
setting_9   0.343062  0.388716  0.388367  0.396687  0.400700  0.350845
setting_10  0.394227  0.344136  0.320558  0.299080  0.312332  0.457626
setting_11  0.547538  0.374360  0.317626  0.508886  0.363934  0.446748
setting_12  0.405848  0.338076  0.412750  0.689082  0.426146  0.495336
setting_13  0.426600  0.441514  0.407961  0.501601  0.705116  0.422946
setting_14  0.406987  0.507453  0.383467  0.322702  0.352189  0.430831
setting_15  0.419002  0.367662  0.457612  0.544028  0.509535  0.528794
setting_16  0.515870  0.389818  0.367979  0.354562  0.351990  0.385240
setting_17  0.389369  0.395882  0.407402  0.416864  0.400460  0.339557
setting_18  0.371203  0.403988  0.301213  0.397334  0.330358  0.500706
setting_19  0.633287  0.371390  0.378677  0.480641  0.460618  0.428558
setting_20  0.354996  0.305884  0.340577  0.683822  0.462282  0.472752
setting_21  0.368785  0.495088  0.430023  0.481095  0.618666  0.462277
setting_22  0.487765  0.460859  0.429035  0.372776  0.429014  0.459082
setting_23  0.377952  0.334124  0.447849  0.422775  0.456285  0.503183
setting_24  0.483077  0.361482  0.399906  0.314663  0.330815  0.389596
setting_25  0.409601  0.432003  0.326942  0.396239  0.384988  0.386471
setting_26  0.359863  0.387278  0.319974  0.504566  0.309594  0.545112
setting_27  0.655435  0.372471  0.404022  0.423928  0.535867  0.446028
setting_28  0.412826  0.273706  0.385442  0.624267  0.574554  0.426402
setting_29  0.282742  0.534319  0.408336  0.434006  0.497439  0.470053
setting_30  0.524153  0.430329  0.446634  0.450920  0.479472  0.458068
setting_31  0.355696  0.298592  0.402288  0.341762  0.384797  0.463045
setting_32  0.492784  0.425815  0.442045  0.377269  0.348860  0.357714
setting_33  0.402527  0.378487  0.312725  0.340092  0.378029  0.423143
setting_34  0.406095  0.350856  0.294823  0.546728  0.302514  0.552757
setting_35  0.624874  0.347379  0.430093  0.489147  0.549074  0.462561
setting_36  0.424603  0.301881  0.360274  0.559415  0.678748  0.380748
setting_37  0.260638  0.560292  0.379249  0.378103  0.383121  0.454627
setting_38  0.515790  0.409868  0.464346  0.518396  0.505667  0.474255
setting_39  0.360915  0.287108  0.379048  0.329903  0.348583  0.414964

## Target: 8

### Classification:

Block #0 Correct output should be 8, classify as 16: **False**

Block #1 Correct output should be 8, classify as 18: **False**

Block #2 Correct output should be 8, classify as 4: **False**

Block #3 Correct output should be 8, classify as 8: **True**

Block #4 Correct output should be 8, classify as 33: **False**

Block #5 Correct output should be 8, classify as 19: **False**

Accuracy: **16.67%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.527615  0.572590  0.621089  0.637484  0.479414  0.478355
setting_1   0.515837  0.401887  0.387236  0.416401  0.410177  0.404840
setting_2   0.294318  0.544552  0.379694  0.341179  0.507989  0.543214
setting_3   0.382140  0.465598  0.387685  0.460466  0.413826  0.530187
setting_4   0.456732  0.588412  0.653398  0.444082  0.412087  0.449658
setting_5   0.455982  0.392467  0.345836  0.360014  0.342842  0.407722
setting_6   0.301014  0.325435  0.384107  0.408924  0.340201  0.450424
setting_7   0.280929  0.318981  0.334575  0.371635  0.311345  0.352065
setting_8   0.610634  0.581435  0.584178  0.662460  0.490325  0.525928
setting_9   0.432305  0.421030  0.328336  0.335952  0.397868  0.409844
setting_10  0.322097  0.631702  0.385617  0.367387  0.477585  0.534365
setting_11  0.372657  0.408949  0.413013  0.481635  0.428054  0.611396
setting_12  0.385369  0.576878  0.607205  0.504955  0.409038  0.376417
setting_13  0.508594  0.386729  0.303950  0.326298  0.371059  0.402471
setting_14  0.295123  0.310789  0.398270  0.353898  0.353011  0.447387
setting_15  0.292872  0.336733  0.337249  0.381912  0.324818  0.382888
setting_16  0.612267  0.521672  0.484279  0.586291  0.502647  0.542371
setting_17  0.311865  0.451259  0.352026  0.356460  0.418145  0.460034
setting_18  0.383172  0.653932  0.358252  0.423084  0.377980  0.534979
setting_19  0.420646  0.432021  0.516296  0.510907  0.378407  0.617688
setting_20  0.318520  0.519500  0.511020  0.540640  0.387131  0.343767
setting_21  0.506152  0.347929  0.336612  0.390986  0.352573  0.379613
setting_22  0.278046  0.353190  0.401679  0.315960  0.358016  0.395376
setting_23  0.300761  0.336617  0.346613  0.371359  0.338924  0.414215
setting_24  0.568416  0.437659  0.500498  0.466789  0.493618  0.409971
setting_25  0.277857  0.437046  0.290111  0.380085  0.476079  0.500997
setting_26  0.417549  0.606156  0.414908  0.485142  0.340142  0.524272
setting_27  0.485036  0.509987  0.586423  0.520021  0.410284  0.596701
setting_28  0.316573  0.450690  0.408779  0.525216  0.351602  0.373649
setting_29  0.442936  0.348522  0.362460  0.352866  0.348943  0.342549
setting_30  0.317643  0.337982  0.409046  0.299132  0.398730  0.340453
setting_31  0.345382  0.378391  0.347847  0.345844  0.363950  0.415883
setting_32  0.549097  0.414393  0.473921  0.408998  0.479961  0.418596
setting_33  0.285370  0.443539  0.319983  0.324227  0.510453  0.510163
setting_34  0.431490  0.544154  0.416228  0.505135  0.417198  0.494452
setting_35  0.501735  0.554214  0.645408  0.464767  0.380395  0.533932
setting_36  0.333770  0.418564  0.367370  0.457533  0.342608  0.397260
setting_37  0.355339  0.351664  0.298744  0.370290  0.306916  0.380773
setting_38  0.311646  0.326963  0.387572  0.340736  0.379064  0.327230
setting_39  0.424216  0.429470  0.373173  0.332700  0.349511  0.394576

## Target: 9

### Classification:

Block #0 Correct output should be 9, classify as 9: **True**

Block #1 Correct output should be 9, classify as 9: **True**

Block #2 Correct output should be 9, classify as 1: **False**

Block #3 Correct output should be 9, classify as 11: **False**

Block #4 Correct output should be 9, classify as 9: **True**

Block #5 Correct output should be 9, classify as 17: **False**

Accuracy: **50.00%**

### Raw Max CC Value (rows are blocks)

                   0         1         2         3         4         5
setting_0   0.483533  0.387034  0.478812  0.509068  0.506986  0.434487
setting_1   0.541865  0.555897  0.615637  0.500669  0.502711  0.591168
setting_2   0.553398  0.346822  0.333846  0.441853  0.411925  0.590370
setting_3   0.511009  0.391779  0.539201  0.505087  0.411966  0.438154
setting_4   0.382999  0.520057  0.424771  0.374163  0.420205  0.493575
setting_5   0.552569  0.469166  0.358569  0.363184  0.389376  0.482415
setting_6   0.303037  0.473482  0.360401  0.327833  0.321570  0.419137
setting_7   0.356513  0.325198  0.379958  0.335007  0.338851  0.303418
setting_8   0.462054  0.455893  0.489721  0.493116  0.422535  0.402710
setting_9   0.646287  0.613108  0.552173  0.504585  0.524427  0.646262
setting_10  0.560289  0.322703  0.361982  0.428427  0.441793  0.578556
setting_11  0.548344  0.412196  0.508266  0.548483  0.373926  0.422019
setting_12  0.298602  0.451650  0.431947  0.346465  0.360895  0.504829
setting_13  0.521401  0.495435  0.387397  0.432844  0.393007  0.407535
setting_14  0.365953  0.449156  0.350541  0.368141  0.289383  0.440493
setting_15  0.310338  0.286740  0.353831  0.338528  0.335949  0.311965
setting_16  0.451512  0.538325  0.499099  0.527739  0.369363  0.455253
setting_17  0.588175  0.518108  0.468050  0.520075  0.450152  0.683586
setting_18  0.496337  0.366391  0.421861  0.413635  0.419307  0.540561
setting_19  0.521625  0.450627  0.456283  0.530953  0.419963  0.418488
setting_20  0.326647  0.380652  0.375568  0.325848  0.364698  0.478203
setting_21  0.431956  0.463008  0.354961  0.431014  0.367480  0.362222
setting_22  0.424000  0.394842  0.334519  0.420590  0.260687  0.389341
setting_23  0.310827  0.335171  0.329126  0.350576  0.348085  0.287854
setting_24  0.462410  0.479516  0.592916  0.469700  0.441385  0.494329
setting_25  0.491392  0.427146  0.429945  0.483864  0.416691  0.668050
setting_26  0.466282  0.357466  0.457772  0.395168  0.403717  0.497391
setting_27  0.487527  0.523037  0.427836  0.489111  0.397897  0.437134
setting_28  0.465022  0.344260  0.368095  0.301474  0.335760  0.455276
setting_29  0.358100  0.453021  0.357867  0.379124  0.410189  0.400902
setting_30  0.443290  0.314283  0.337106  0.418053  0.335206  0.360375
setting_31  0.334639  0.344961  0.346985  0.382514  0.306676  0.311937
setting_32  0.422205  0.511425  0.611187  0.488514  0.490298  0.529169
setting_33  0.525225  0.330449  0.327731  0.414497  0.430282  0.591748
setting_34  0.469940  0.370162  0.525698  0.433205  0.386251  0.488515
setting_35  0.449497  0.543318  0.437836  0.404758  0.420443  0.435353
setting_36  0.544006  0.405422  0.361709  0.316404  0.364734  0.496000
setting_37  0.314228  0.493536  0.359277  0.329282  0.344293  0.366944
setting_38  0.413192  0.303116  0.364609  0.372254  0.320665  0.361102
setting_39  0.340296  0.314864  0.294955  0.409222  0.300256  0.287860